/**
 * data.js — Digital Armory
 * Complete local dataset. No network requests.
 * Stats are on a 0-100 normalised scale for bar rendering.
 * rawStats hold real-world values for display.
 */

'use strict';

window.ARMORY_DATA = [

    /* ══════════════════════════════════════════════════════════════
       LAND FORCES
    ══════════════════════════════════════════════════════════════ */
    {
        id: 'M1A2', name: 'M1A2 Abrams', designation: 'MBT', category: 'land',
        emoji: '🛡', origin: 'USA', era: 'Modern', status: 'active', year: 1986,
        description: 'The M1A2 Abrams is the US Army\'s main battle tank, featuring Chobham composite armour, a 120mm smoothbore cannon, and advanced thermal imaging systems. Widely regarded as one of the most formidable ground vehicles in service.',
        specs: { weight:'62 t', crew:'4', engine:'1,500hp turbine', armament:'120mm M256 cannon' },
        stats: { armor:95, speed:62, range:45, firepower:90 },
        rawStats: { armor:'Chobham + DU', speed:'72 km/h', range:'426 km', firepower:'120mm APFSDS' },
        tags: ['heavy', 'NATO', 'composite armour', 'gas turbine'],
    },
    {
        id: 'T90', name: 'T-90M Proryv', designation: 'MBT', category: 'land',
        emoji: '⚔', origin: 'Russia', era: 'Modern', status: 'active', year: 2017,
        description: 'The T-90M "Breakthrough" is Russia\'s most advanced T-series tank, combining a 125mm cannon, Relikt ERA, and the Shtora active protection system. Represents the pinnacle of Soviet armour heritage modernised for contemporary warfare.',
        specs: { weight:'48 t', crew:'3', engine:'1,130hp diesel', armament:'125mm 2A46M-4' },
        stats: { armor:82, speed:68, range:55, firepower:85 },
        rawStats: { armor:'Relikt ERA + composite', speed:'65 km/h', range:'550 km', firepower:'125mm APFSDS-T' },
        tags: ['ERA', 'autoloader', 'Russia', 'active protection'],
    },
    {
        id: 'LEOPARD2A7', name: 'Leopard 2A7+', designation: 'MBT', category: 'land',
        emoji: '🛡', origin: 'Germany', era: 'Modern', status: 'active', year: 2014,
        description: 'Germany\'s premier main battle tank, the Leopard 2A7+ boasts exceptional firepower accuracy, enhanced armour packages for urban warfare, and state-of-the-art command systems. Operated by over 20 nations.',
        specs: { weight:'68 t', crew:'4', engine:'1,500hp MTU MB 873', armament:'120mm Rheinmetall L/55' },
        stats: { armor:92, speed:68, range:50, firepower:93 },
        rawStats: { armor:'MEXAS composite', speed:'72 km/h', range:'500 km', firepower:'120mm L/55' },
        tags: ['NATO', 'Germany', 'export', 'hunter-killer'],
    },
    {
        id: 'TYPE99A', name: 'Type 99A', designation: 'MBT', category: 'land',
        emoji: '⚔', origin: 'China', era: 'Modern', status: 'active', year: 2011,
        description: 'China\'s most advanced main battle tank, featuring a modular armour system, active protection, and digital battlefield management. Represents a major leap in Chinese armoured warfare capability.',
        specs: { weight:'54 t', crew:'3', engine:'1,500hp diesel', armament:'125mm ZPT-98A' },
        stats: { armor:80, speed:70, range:52, firepower:82 },
        rawStats: { armor:'Modular composite + ERA', speed:'80 km/h', range:'500 km', firepower:'125mm APFSDS' },
        tags: ['China', 'PLA', 'modern', 'autoloader'],
    },
    {
        id: 'CHALLENGER3', name: 'Challenger 3', designation: 'MBT', category: 'land',
        emoji: '🛡', origin: 'UK', era: 'Modern', status: 'limited', year: 2027,
        description: 'Britain\'s next-generation upgrade to the Challenger 2, featuring a new 120mm L/55A1 cannon, hunter-killer optics, and a digital turret. Designed to remain competitive into the 2040s.',
        specs: { weight:'67 t', crew:'4', engine:'1,200hp Perkins CV12', armament:'120mm L/55A1' },
        stats: { armor:93, speed:58, range:48, firepower:91 },
        rawStats: { armor:'Dorchester composite', speed:'59 km/h', range:'450 km', firepower:'120mm APFSDS' },
        tags: ['UK', 'NATO', 'rifled cannon', 'upgrade'],
    },
    {
        id: 'BRADLEYIFW', name: 'Bradley IFV (M2A4)', designation: 'IFV', category: 'land',
        emoji: '🚛', origin: 'USA', era: 'Modern', status: 'active', year: 1981,
        description: 'The Bradley Infantry Fighting Vehicle combines firepower with troop transport, armed with a 25mm Bushmaster chain gun and TOW anti-tank missiles. A cornerstone of US Army mechanised infantry doctrine.',
        specs: { weight:'33 t', crew:'3 + 6', engine:'600hp Cummins VTA-903T', armament:'25mm M242 + TOW' },
        stats: { armor:60, speed:72, range:60, firepower:70 },
        rawStats: { armor:'Aluminium + MEXAS', speed:'66 km/h', range:'483 km', firepower:'25mm + TOW ATGM' },
        tags: ['IFV', 'USA', 'amphibious', 'chain gun'],
    },
    {
        id: 'PZHHOW', name: 'PzH 2000', designation: 'SPH', category: 'land',
        emoji: '💣', origin: 'Germany', era: 'Modern', status: 'active', year: 1998,
        description: 'The Panzerhaubitze 2000 is widely considered the world\'s most capable self-propelled howitzer. Its 155mm gun can fire 3 rounds in 9 seconds and has an automatic loading system for a crew-minimised operation.',
        specs: { weight:'55 t', crew:'5', engine:'986hp MTU diesel', armament:'155mm L/52 howitzer' },
        stats: { armor:45, speed:62, range:88, firepower:96 },
        rawStats: { armor:'Steel hull', speed:'60 km/h', range:'420 km', firepower:'155mm / 56 km range' },
        tags: ['artillery', 'Germany', 'precision', 'NATO'],
    },
    {
        id: 'STRYKER', name: 'Stryker MGS', designation: 'ARV', category: 'land',
        emoji: '🚛', origin: 'USA', era: 'Modern', status: 'active', year: 2002,
        description: 'The Stryker Mobile Gun System is a wheeled armoured vehicle mounting a 105mm tank gun. Designed for rapid deployment and urban warfare, it bridges the gap between light forces and armour.',
        specs: { weight:'20 t', crew:'3', engine:'350hp Caterpillar', armament:'105mm M68A2' },
        stats: { armor:48, speed:85, range:75, firepower:68 },
        rawStats: { armor:'Slat + MEXAS add-on', speed:'100 km/h', range:'530 km', firepower:'105mm HEAT/APFSDS' },
        tags: ['wheeled', 'USA', 'rapid deployment', 'urban'],
    },
    {
        id: 'K2BLACK', name: 'K2 Black Panther', designation: 'MBT', category: 'land',
        emoji: '⚔', origin: 'South Korea', era: 'Modern', status: 'active', year: 2014,
        description: 'The K2 Black Panther is South Korea\'s indigenous main battle tank, featuring a hydropneumatic suspension, 1,500hp diesel engine, and an indigenous APS. One of the most expensive and capable tanks in service.',
        specs: { weight:'55 t', crew:'3', engine:'1,500hp diesel', armament:'120mm CN08' },
        stats: { armor:88, speed:78, range:55, firepower:90 },
        rawStats: { armor:'Korean composite + ERA', speed:'70 km/h', range:'450 km', firepower:'120mm APFSDS-T' },
        tags: ['Korea', 'autoloader', 'APS', 'hydropneumatic'],
    },
    {
        id: 'APACHEHELO', name: 'AH-64E Apache Guardian', designation: 'AH', category: 'air',
        emoji: '🚁', origin: 'USA', era: 'Modern', status: 'active', year: 1998,
        description: 'The AH-64E Apache Guardian is the premier American attack helicopter, armed with Hellfire missiles, Hydra 70 rockets, and a 30mm chain gun. The Guardian variant adds Link 16 and ability to control UAVs.',
        specs: { weight:'8.0 t', crew:'2', engine:'2x GE T700-701D', armament:'30mm M230 + Hellfire' },
        stats: { armor:28, speed:72, range:58, firepower:88 },
        rawStats: { armor:'Armoured cockpit', speed:'293 km/h', range:'480 km', firepower:'30mm + 16x Hellfire' },
        tags: ['rotary', 'USA', 'anti-tank', 'night capable'],
    },

    /* ══════════════════════════════════════════════════════════════
       AIR FORCES
    ══════════════════════════════════════════════════════════════ */
    {
        id: 'F22', name: 'F-22A Raptor', designation: 'F-22A', category: 'air',
        emoji: '✈', origin: 'USA', era: 'Modern', status: 'active', year: 2005,
        description: 'The F-22A Raptor is the USAF\'s premier air-superiority stealth fighter, combining supercruise capability, thrust vectoring, and an advanced AESA radar. Its all-aspect stealth makes detection by conventional radar nearly impossible.',
        specs: { weight:'19.7 t', crew:'1', engine:'2x F119-PW-100', armament:'AIM-120C/D, AIM-9X, M61A2' },
        stats: { armor:30, speed:98, range:62, firepower:92 },
        rawStats: { armor:'Stealth coating', speed:'Mach 2.25 / 2,410 km/h', range:'2,960 km', firepower:'AIM-120 + M61A2 20mm' },
        tags: ['stealth', 'supercruise', 'USA', '5th gen', 'air superiority'],
    },
    {
        id: 'F35', name: 'F-35A Lightning II', designation: 'F-35A', category: 'air',
        emoji: '✈', origin: 'USA', era: 'Modern', status: 'active', year: 2015,
        description: 'The F-35A Lightning II is a multirole 5th-generation stealth fighter designed for both air-to-air and air-to-ground missions. Operated by 18 nations, it is the most widely deployed advanced stealth aircraft in history.',
        specs: { weight:'13.3 t', crew:'1', engine:'F135-PW-100', armament:'AIM-120, AIM-9X, GBU-53, GAU-22' },
        stats: { armor:28, speed:88, range:78, firepower:90 },
        rawStats: { armor:'DAS + stealth', speed:'Mach 1.6 / 1,960 km/h', range:'2,220 km', firepower:'Multirole payload 8,160 kg' },
        tags: ['stealth', '5th gen', 'multirole', 'NATO', 'STOVL variant'],
    },
    {
        id: 'SU57', name: 'Su-57 Felon', designation: 'Su-57', category: 'air',
        emoji: '✈', origin: 'Russia', era: 'Modern', status: 'limited', year: 2019,
        description: 'Russia\'s first 5th-generation stealth fighter, the Su-57 Felon features supercruise capability, internal weapons bays, and advanced avionics. Currently in limited production with the Russian Aerospace Forces.',
        specs: { weight:'18.5 t', crew:'1', engine:'2x AL-41F1 (Izdeliye 30)', armament:'30mm GSh-30-1, R-77M, Kh-35' },
        stats: { armor:32, speed:96, range:68, firepower:88 },
        rawStats: { armor:'RAM coating', speed:'Mach 2.0 / 2,120 km/h', range:'3,500 km', firepower:'30mm cannon + BVR missiles' },
        tags: ['stealth', 'Russia', '5th gen', 'supercruise', 'thrust vectoring'],
    },
    {
        id: 'EUROFIGHTER', name: 'Eurofighter Typhoon', designation: 'EF-2000', category: 'air',
        emoji: '✈', origin: 'UK/Germany', era: 'Modern', status: 'active', year: 2003,
        description: 'The Eurofighter Typhoon is a twin-engine canard-delta wing multirole fighter. A joint project between the UK, Germany, Spain and Italy, it provides excellent agility and BVR missile capability.',
        specs: { weight:'11.0 t', crew:'1-2', engine:'2x EJ200', armament:'27mm Mauser BK-27, Meteor, AMRAAM' },
        stats: { armor:22, speed:92, range:66, firepower:84 },
        rawStats: { armor:'Composite airframe', speed:'Mach 2.0 / 2,125 km/h', range:'2,900 km', firepower:'Meteor + AMRAAM' },
        tags: ['multirole', 'NATO', 'canard', 'swing-role'],
    },
    {
        id: 'B2SPIRIT', name: 'B-2A Spirit', designation: 'B-2A', category: 'air',
        emoji: '✈', origin: 'USA', era: 'Modern', status: 'active', year: 1997,
        description: 'The Northrop Grumman B-2A Spirit is the USAF\'s primary stealth strategic bomber. Its flying-wing design and advanced RAM coatings give it a radar cross-section comparable to a large bird, enabling deep penetration strikes.',
        specs: { weight:'70.5 t', crew:'2', engine:'4x GE F118-GE-100', armament:'JDAM, B83/B61 nuclear, GBU-57 MOP' },
        stats: { armor:18, speed:65, range:96, firepower:99 },
        rawStats: { armor:'Full-spectrum stealth', speed:'1,010 km/h', range:'11,100 km (unrefuelled)', firepower:'40,000 lb payload' },
        tags: ['stealth', 'strategic', 'nuclear', 'flying wing', 'USA'],
    },
    {
        id: 'A10', name: 'A-10C Thunderbolt II', designation: 'A-10C', category: 'air',
        emoji: '✈', origin: 'USA', era: 'Cold War', status: 'active', year: 1977,
        description: 'The A-10C "Warthog" is the USAF\'s dedicated CAS platform. Built around the GAU-8 30mm Avenger rotary cannon, it can absorb tremendous battle damage due to its titanium tub cockpit and redundant systems.',
        specs: { weight:'12.3 t', crew:'1', engine:'2x TF34-GE-100A', armament:'GAU-8 30mm, Mavericks, GBU-12' },
        stats: { armor:42, speed:55, range:65, firepower:86 },
        rawStats: { armor:'Ti tub + foam-filled tanks', speed:'706 km/h', range:'1,280 km (combat)', firepower:'GAU-8 3,900 rd/min' },
        tags: ['CAS', 'tank buster', 'survivable', 'USA', 'gun aircraft'],
    },
    {
        id: 'RAFALE', name: 'Dassault Rafale F4', designation: 'Rafale F4', category: 'air',
        emoji: '✈', origin: 'France', era: 'Modern', status: 'active', year: 2001,
        description: 'France\'s indigenous omnirole fighter, the Rafale is known for its carrier compatibility, ASMP-A nuclear delivery role, and unmatched mission flexibility. The F4 standard adds Link 22 and Talios targeting.',
        specs: { weight:'10.3 t', crew:'1-2', engine:'2x M88-4E', armament:'30mm GIAT 791B, Meteor, SCALP-EG' },
        stats: { armor:20, speed:90, range:72, firepower:86 },
        rawStats: { armor:'Composite + stealth features', speed:'Mach 1.8 / 1,912 km/h', range:'3,700 km', firepower:'14,700 lb payload' },
        tags: ['omnirole', 'France', 'carrier capable', 'nuclear delivery'],
    },
    {
        id: 'SR71', name: 'SR-71 Blackbird', designation: 'SR-71A', category: 'air',
        emoji: '✈', origin: 'USA', era: 'Cold War', status: 'retired', year: 1966,
        description: 'The SR-71 Blackbird was the fastest manned airbreathing aircraft ever built. Capable of outrunning missiles with sheer speed, it conducted strategic reconnaissance missions throughout the Cold War until its retirement in 1998.',
        specs: { weight:'30.6 t', crew:'2', engine:'2x Pratt & Whitney J58', armament:'None (reconnaissance)' },
        stats: { armor:8, speed:100, range:82, firepower:0 },
        rawStats: { armor:'Titanium RAM skin', speed:'Mach 3.3+ / 3,530 km/h', range:'5,400 km', firepower:'Unarmed' },
        tags: ['reconnaissance', 'Cold War', 'fastest', 'USA', 'retired'],
    },
    {
        id: 'F16', name: 'F-16C Block 70 Viper', designation: 'F-16C', category: 'air',
        emoji: '✈', origin: 'USA', era: 'Modern', status: 'active', year: 1978,
        description: 'The F-16 Fighting Falcon, or "Viper," is one of the most successful and widely operated combat aircraft in history. Block 70 adds AESA radar, JHMCS II, and conformal fuel tanks, giving it formidable 4.5-gen capability.',
        specs: { weight:'8.6 t', crew:'1', engine:'F110-GE-129', armament:'M61A1, AIM-9X, AIM-120D, JDAM' },
        stats: { armor:18, speed:88, range:65, firepower:80 },
        rawStats: { armor:'Composite airframe', speed:'Mach 2.05 / 2,173 km/h', range:'3,220 km', firepower:'7,700 kg payload' },
        tags: ['multirole', 'NATO', 'export champion', '4th gen', 'dogfighter'],
    },
    {
        id: 'V22', name: 'Bell Boeing V-22 Osprey', designation: 'MV-22B', category: 'air',
        emoji: '🚁', origin: 'USA', era: 'Modern', status: 'active', year: 2007,
        description: 'The V-22 Osprey is a tiltrotor aircraft combining helicopter and turboprop capabilities. Used by USMC and USSOCOM for long-range assault missions, it cruises at fixed-wing speeds but lands and takes off vertically.',
        specs: { weight:'15.0 t', crew:'4 + 24 troops', engine:'2x Rolls-Royce AE1107C', armament:'7.62mm M240 or .50 cal' },
        stats: { armor:15, speed:82, range:80, firepower:20 },
        rawStats: { armor:'Composite airframe', speed:'565 km/h', range:'1,627 km', firepower:'Defensive armament' },
        tags: ['tiltrotor', 'USA', 'special ops', 'VSTOL', 'amphibious assault'],
    },

    /* ══════════════════════════════════════════════════════════════
       NAVAL FORCES
    ══════════════════════════════════════════════════════════════ */
    {
        id: 'GERALDFORD', name: 'Gerald R. Ford (CVN-78)', designation: 'CVN-78', category: 'sea',
        emoji: '⚓', origin: 'USA', era: 'Modern', status: 'active', year: 2017,
        description: 'The world\'s largest and most capable aircraft carrier, CVN-78 features EMALS catapults, AAG arresting gear, and 11 decks of aviation facilities. With a 90-aircraft air wing, it projects American power globally.',
        specs: { weight:'100,000 t', crew:'4,500 + 2,500 air wing', engine:'2x A1B nuclear reactors', armament:'Air wing, RIM-162 ESSM, Phalanx CIWS' },
        stats: { armor:72, speed:58, range:100, firepower:98 },
        rawStats: { armor:'4-inch armoured deck zones', speed:'30+ kts / 56 km/h', range:'Unlimited (nuclear)', firepower:'90-aircraft wing' },
        tags: ['nuclear', 'USA', 'supercarrier', 'power projection', 'EMALS'],
    },
    {
        id: 'VIRGINIACLASS', name: 'Virginia-class SSN (Block V)', designation: 'SSN', category: 'sea',
        emoji: '🌊', origin: 'USA', era: 'Modern', status: 'active', year: 2004,
        description: 'The Virginia-class is the US Navy\'s primary fast-attack submarine. Block V adds the Virginia Payload Module (VPM) for 28 additional VLS cells, giving it a massive strike capacity alongside its traditional torpedo armament.',
        specs: { weight:'10,200 t', crew:'135', engine:'1x S9G nuclear reactor', armament:'Mk 48 ADCAP, TLAM, Harpoon, 40 VLS' },
        stats: { armor:65, speed:62, range:100, firepower:92 },
        rawStats: { armor:'HY-100 steel hull', speed:'25+ kts (submerged)', range:'Unlimited (nuclear)', firepower:'40 VLS + 4 torpedo tubes' },
        tags: ['nuclear', 'USA', 'SSN', 'TLAM', 'stealth'],
    },
    {
        id: 'ARLEIGHBURKE', name: 'Arleigh Burke DDG (Flight III)', designation: 'DDG-51', category: 'sea',
        emoji: '⚓', origin: 'USA', era: 'Modern', status: 'active', year: 1991,
        description: 'The Arleigh Burke-class guided-missile destroyer is the backbone of the US Navy. Flight III adds the AN/SPY-6(V)1 Air and Missile Defense Radar, the world\'s most capable destroyer radar, increasing detection range by 35x.',
        specs: { weight:'9,700 t', crew:'329', engine:'4x GE LM2500 turbines', armament:'96-cell VLS, 5-inch gun, Harpoon, CIWS, Mk54 torpedo' },
        stats: { armor:55, speed:72, range:75, firepower:88 },
        rawStats: { armor:'Kevlar over vital systems', speed:'30+ kts / 56 km/h', range:'8,230 km', firepower:'96 VLS cells (SM-3/6, TLAM)' },
        tags: ['DDG', 'USA', 'Aegis', 'BMD', 'NATO', 'ABM'],
    },
    {
        id: 'KUZNETSOV', name: 'Admiral Kuznetsov (CV)', designation: 'TAKR', category: 'sea',
        emoji: '⚓', origin: 'Russia', era: 'Modern', status: 'limited', year: 1990,
        description: 'Russia\'s sole aircraft carrier, the Kuznetsov is a hybrid aviation-cruiser capable of carrying Flanker fighters and armed with P-700 Granit anti-ship missiles. Currently undergoing refit with new turbines and STOBAR systems.',
        specs: { weight:'61,390 t', crew:'1,960 + 626 air wing', engine:'8x steam turbines (+ diesel)', armament:'P-700 Granit, CADS-N-1, Su-33/MiG-29K' },
        stats: { armor:70, speed:48, range:72, firepower:82 },
        rawStats: { armor:'Armoured magazine citadel', speed:'29 kts / 54 km/h', range:'8,500 km', firepower:'12x P-700 + 52 aircraft' },
        tags: ['carrier', 'Russia', 'STOBAR', 'P-700', 'hybrid cruiser'],
    },
    {
        id: 'TYPHOONSUBM', name: 'Typhoon-class SSBN (TK-208)', designation: 'SSBN', category: 'sea',
        emoji: '🌊', origin: 'Russia', era: 'Cold War', status: 'limited', year: 1981,
        description: 'The Typhoon remains the largest submarine ever constructed. Carrying 20 R-39 SLBMs each with 10 MIRVs, a single boat could threaten an entire hemisphere. The class is largely retired, with TK-208 retained as test platform.',
        specs: { weight:'48,000 t (subm)', crew:'160', engine:'2x OK-650 nuclear reactors', armament:'20x R-39 SLBM, 6x 533mm torpedo' },
        stats: { armor:70, speed:50, range:100, firepower:99 },
        rawStats: { armor:'7.2m double hull', speed:'27 kts / 50 km/h', range:'Unlimited (nuclear)', firepower:'20x SLBM / 200 MIRVs' },
        tags: ['SSBN', 'nuclear', 'Russia', 'MIRV', 'Cold War', 'largest'],
    },
    {
        id: 'QUEEN_ELIZ', name: 'HMS Queen Elizabeth (R08)', designation: 'CVF', category: 'sea',
        emoji: '⚓', origin: 'UK', era: 'Modern', status: 'active', year: 2017,
        description: 'HMS Queen Elizabeth is the UK\'s largest ever warship and leads the Carrier Strike Group alongside Type 45 destroyers. Her STOVL deck accommodates the F-35B Lightning II, delivering 5th-generation capability from a carrier deck.',
        specs: { weight:'65,000 t', crew:'1,600 + air wing', engine:'Gas turbine + diesel-electric', armament:'F-35B, Phalanx CIWS, Miniguns, LMM' },
        stats: { armor:58, speed:60, range:88, firepower:88 },
        rawStats: { armor:'Armoured flight deck sections', speed:'25 kts / 46 km/h', range:'10,000 nm', firepower:'36x F-35B' },
        tags: ['UK', 'carrier', 'STOVL', 'F-35B', 'strike group'],
    },
    {
        id: 'ZUMWALT', name: 'USS Zumwalt (DDG-1000)', designation: 'DDG-1000', category: 'sea',
        emoji: '⚓', origin: 'USA', era: 'Modern', status: 'active', year: 2016,
        description: 'The Zumwalt-class destroyer features a tumblehome hull for reduced radar cross-section, all-electric propulsion, and originally the Advanced Gun System. Now being converted to carry Conventional Prompt Strike hypersonic missiles.',
        specs: { weight:'14,564 t', crew:'147', engine:'Integrated electric drive (78 MW)', armament:'2x AGS/CPS launchers, 80 VLS, Mk 46 torpedo' },
        stats: { armor:50, speed:68, range:78, firepower:90 },
        rawStats: { armor:'Advanced enclosed mast stealth', speed:'30 kts / 56 km/h', range:'14,000 km', firepower:'CPS hypersonic + 80 VLS' },
        tags: ['stealth', 'USA', 'DDG', 'electric drive', 'hypersonic', 'future'],
    },
    {
        id: 'KILOCLASS', name: 'Kilo-class SSK (Project 636)', designation: 'SSK', category: 'sea',
        emoji: '🌊', origin: 'Russia', era: 'Modern', status: 'active', year: 1982,
        description: 'NATO calls the Project 636 Varshavyanka the "Black Hole" submarine due to its ultra-quiet diesel-electric propulsion. Armed with Kalibr cruise missiles, it has proven devastating in conflict and is exported widely.',
        specs: { weight:'3,950 t', crew:'52', engine:'2x 2D42 diesel + electric motors', armament:'6x 533mm tubes, 18 torpedoes/Kalibr' },
        stats: { armor:40, speed:42, range:60, firepower:75 },
        rawStats: { armor:'Double-hull sound dampening', speed:'17 kts / 31 km/h', range:'7,000 km snorkel', firepower:'Kalibr LACM 1,500 km range' },
        tags: ['SSK', 'diesel-electric', 'Russia', 'Kalibr', 'export', 'stealth'],
    },
    {
        id: 'IZUMO', name: 'JS Izumo (DDH-183)', designation: 'DDH', category: 'sea',
        emoji: '⚓', origin: 'Japan', era: 'Modern', status: 'active', year: 2015,
        description: 'Originally designated a helicopter destroyer, the Izumo is being converted to operate F-35B fighters, effectively making Japan\'s Maritime Self-Defense Force a carrier-capable force for the first time since WWII.',
        specs: { weight:'26,000 t', crew:'470 + air wing', engine:'COGAG: 4x LM2500 turbines', armament:'SeaRAM, RUM-139, F-35B (converting)' },
        stats: { armor:40, speed:68, range:78, firepower:72 },
        rawStats: { armor:'Composite flight deck', speed:'30 kts / 56 km/h', range:'11,000 km', firepower:'14x F-35B (converting) + helicopters' },
        tags: ['Japan', 'DDH', 'F-35B conversion', 'carrier', 'self-defense'],
    },
    {
        id: 'FRIDTJOF', name: 'HNoMS Fridtjof Nansen (F310)', designation: 'FFG', category: 'sea',
        emoji: '⚓', origin: 'Norway', era: 'Modern', status: 'active', year: 2006,
        description: 'The Fridtjof Nansen-class frigate is Norway\'s most advanced surface combatant, based on the Spanish F-100 design with an Aegis Combat System and unique Norwegian Strike Missile (NSM) integration for shore-attack.',
        specs: { weight:'5,290 t', crew:'120', engine:'CODAG: 1x GE LM2500 + diesels', armament:'NSM, ESSM, Sting Ray, 76mm OTO' },
        stats: { armor:35, speed:72, range:70, firepower:78 },
        rawStats: { armor:'Reduced RCS superstructure', speed:'26 kts / 48 km/h', range:'8,000+ km', firepower:'NSM + 32-cell ESSM' },
        tags: ['Norway', 'FFG', 'NSM', 'Aegis', 'NATO'],
    },

    /* ── Additional entries ────────────────────────────────────── */
    {
        id: 'ABRAMS_M60', name: 'M60A3 Patton', designation: 'MBT', category: 'land',
        emoji: '⚔', origin: 'USA', era: 'Cold War', status: 'retired', year: 1960,
        description: 'The M60 Patton served as the US Army\'s main battle tank throughout the Cold War. The A3 variant added a laser rangefinder and improved fire control, seeing action in the 1991 Gulf War with allied nations.',
        specs: { weight:'54 t', crew:'4', engine:'750hp AVDS-1790-2C diesel', armament:'105mm M68 cannon' },
        stats: { armor:65, speed:52, range:58, firepower:70 },
        rawStats: { armor:'Cast steel composite', speed:'48 km/h', range:'480 km', firepower:'105mm APDS/HEAT' },
        tags: ['Cold War', 'USA', 'retired', 'NATO', 'Gulf War'],
    },
    {
        id: 'MI28', name: 'Mil Mi-28N Night Hunter', designation: 'Mi-28N', category: 'air',
        emoji: '🚁', origin: 'Russia', era: 'Modern', status: 'active', year: 2008,
        description: 'Russia\'s primary attack helicopter and successor to the Mi-24 Hind. The Mi-28N "Night Hunter" features all-weather night operations, a 30mm autocannon, and Vikhr anti-tank missiles. Proven in Syria.',
        specs: { weight:'8.1 t', crew:'2', engine:'2x Klimov TV3-117VMA', armament:'30mm 2A42, Ataka/Vikhr ATGM' },
        stats: { armor:32, speed:68, range:52, firepower:82 },
        rawStats: { armor:'Armoured cockpit + rotor blades', speed:'324 km/h', range:'460 km', firepower:'30mm + 16x ATGM' },
        tags: ['rotary', 'Russia', 'night capable', 'anti-tank'],
    },
    {
        id: 'NIMITZCLASS', name: 'USS Nimitz (CVN-68)', designation: 'CVN-68', category: 'sea',
        emoji: '⚓', origin: 'USA', era: 'Cold War', status: 'active', year: 1975,
        description: 'Lead ship of the Nimitz class, CVN-68 is the oldest active nuclear-powered carrier in the US fleet. With over 50 years of service, the Nimitz class forms the core of American naval aviation power with 10 hulls still in service.',
        specs: { weight:'104,600 t', crew:'5,000 + 2,500 air wing', engine:'2x A4W nuclear reactors', armament:'90-aircraft air wing, ESSM, CIWS, RIM-7' },
        stats: { armor:68, speed:56, range:100, firepower:96 },
        rawStats: { armor:'3-inch armoured flight deck', speed:'30+ kts', range:'Unlimited (nuclear)', firepower:'90-aircraft wing' },
        tags: ['nuclear', 'USA', 'supercarrier', 'Cold War', 'power projection'],
    },
    {
        id: 'OSPREY_MCH', name: 'MH-60R Seahawk', designation: 'MH-60R', category: 'air',
        emoji: '🚁', origin: 'USA', era: 'Modern', status: 'active', year: 2001,
        description: 'The MH-60R Seahawk is the US Navy\'s primary anti-submarine and anti-surface warfare helicopter. Equipped with dipping sonar, sonobuoys, and Mk54 torpedoes, it is one of the most capable naval helicopters in service.',
        specs: { weight:'6.9 t', crew:'4', engine:'2x GE T700-GE-401C', armament:'Mk54 torpedoes, AGM-114 Hellfire, M60' },
        stats: { armor:15, speed:65, range:55, firepower:60 },
        rawStats: { armor:'Composite airframe', speed:'270 km/h', range:'834 km', firepower:'Torpedoes + Hellfire' },
        tags: ['rotary', 'ASW', 'USA', 'naval aviation', 'carrier based'],
    },
    {
        id: 'PATRIOTMDS', name: 'Patriot PAC-3 MDS', designation: 'MIM-104F', category: 'land',
        emoji: '🚀', origin: 'USA', era: 'Modern', status: 'active', year: 1984,
        description: 'The Patriot PAC-3 MSE (Missile Segment Enhancement) is NATO\'s premier ground-based air defense system. Capable of intercepting tactical ballistic missiles, cruise missiles, and advanced aircraft. Proven in multiple conflicts.',
        specs: { weight:'2,000 kg (launcher)', crew:'90 (battery)', engine:'N/A (ground system)', armament:'PAC-3 MSE interceptors, GEM-T' },
        stats: { armor:20, speed:0, range:82, firepower:88 },
        rawStats: { armor:'Vehicle armour only', speed:'Static', range:'100+ km intercept', firepower:'PAC-3 MSE hit-to-kill' },
        tags: ['SAM', 'USA', 'NATO', 'ABM', 'air defense', 'BMD'],
    },
    {
        id: 'HMSTYPE45', name: 'HMS Daring (D32)', designation: 'Type 45', category: 'sea',
        emoji: '⚓', origin: 'UK', era: 'Modern', status: 'active', year: 2009,
        description: 'The Type 45 destroyer is the Royal Navy\'s air-warfare specialist, built around the SAMPSON AESA radar and Sea Viper (Aster 30) missile system. Designed to protect carrier groups from advanced air threats, including ballistic missiles.',
        specs: { weight:'8,500 t', crew:'190', engine:'WR-21 intercooled gas turbine + diesel-electric', armament:'Sea Viper (Aster 15/30), 4.5-inch gun, Harpoon, CIWS' },
        stats: { armor:42, speed:68, range:72, firepower:82 },
        rawStats: { armor:'Reduced RCS superstructure', speed:'29 kts / 54 km/h', range:'7,000+ km', firepower:'Aster 30 (120 km range)' },
        tags: ['UK', 'DDG', 'air warfare', 'Aster', 'Sea Viper', 'ABM'],
    },
    {
        id: 'F117', name: 'F-117A Nighthawk', designation: 'F-117A', category: 'air',
        emoji: '✈', origin: 'USA', era: 'Cold War', status: 'retired', year: 1983,
        description: 'The world\'s first operational stealth aircraft, the F-117A used faceted geometry and RAM coatings to drastically reduce radar signature. Despite being named a fighter, it was a pure strike aircraft with no air-to-air capability.',
        specs: { weight:'10.4 t', crew:'1', engine:'2x GE F404-GE-F1D2', armament:'2x GBU-10/27 laser-guided bombs' },
        stats: { armor:12, speed:52, range:62, firepower:72 },
        rawStats: { armor:'RAM faceted panels', speed:'1,040 km/h', range:'1,720 km', firepower:'2x 2,000 lb precision bombs' },
        tags: ['stealth', 'Cold War', 'USA', 'retired', 'strike', 'pioneer'],
    },
    {
        id: 'OSAACLASS', name: 'Osa II (Project 205P)', designation: 'FAC-M', category: 'sea',
        emoji: '⚓', origin: 'Russia', era: 'Cold War', status: 'retired', year: 1965,
        description: 'The Osa-class missile boat was the quintessential Cold War fast attack craft, arming small hulls with powerful Styx anti-ship missiles. Exported worldwide and used in several Middle East conflicts.',
        specs: { weight:'210 t', crew:'30', engine:'3x M503A diesels', armament:'4x P-15 Termit (NATO: Styx)' },
        stats: { armor:12, speed:88, range:32, firepower:62 },
        rawStats: { armor:'Minimal steel hull', speed:'36 kts / 67 km/h', range:'800 km', firepower:'4x P-15 Styx 80 km range' },
        tags: ['FAC-M', 'Russia', 'Cold War', 'export', 'retired', 'missile boat'],
    },
    {
        id: 'AGM158JASSM', name: 'AGM-158B JASSM-ER', designation: 'AGM-158B', category: 'air',
        emoji: '🚀', origin: 'USA', era: 'Modern', status: 'active', year: 2014,
        description: 'The Joint Air-to-Surface Standoff Missile Extended Range (JASSM-ER) is a low-observable cruise missile with a 926 km range. Carried by B-1B, B-52, F-15E, and F/A-18E/F, it enables standoff strikes against heavily defended targets.',
        specs: { weight:'1,090 kg', crew:'N/A (autonomous)', engine:'Williams F107-WR-105 turbofan', armament:'450 kg WDU-42/B warhead' },
        stats: { armor:8, speed:72, range:95, firepower:86 },
        rawStats: { armor:'Stealth airframe', speed:'~High subsonic Mach 0.85', range:'926 km', firepower:'450 kg blast fragmentation' },
        tags: ['cruise missile', 'USA', 'standoff', 'stealth', 'precision', 'NATO'],
    },
    {
        id: 'KIROV', name: 'Kirov-class Battlecruiser (Pyotr Velikiy)', designation: 'CGN', category: 'sea',
        emoji: '⚓', origin: 'Russia', era: 'Cold War', status: 'active', year: 1980,
        description: 'The Kirov-class (Project 1144) is the largest and most heavily armed surface combatant in the world, displacing over 28,000 tonnes. Armed with P-700 Granit missiles, S-300FM SAMs, and a nuclear reactor, it is a fleet in a single hull.',
        specs: { weight:'28,000 t', crew:'727', engine:'2x nuclear reactors + steam turbines', armament:'20x P-700 Granit, 96x S-300FM, 130mm gun' },
        stats: { armor:80, speed:62, range:100, firepower:96 },
        rawStats: { armor:'Armoured citadel', speed:'32 kts / 59 km/h', range:'Unlimited (nuclear)', firepower:'20x P-700 + 512-cell air defense' },
        tags: ['nuclear', 'Russia', 'battlecruiser', 'Cold War', 'P-700', 'largest'],
    },
];

/* ── Helpers consumed by ui.js ──────────────────────────────── */
window.ARMORY_HELPERS = {
    /** Get unique sorted list of a field */
    unique(field) {
        return [...new Set(window.ARMORY_DATA.map(d => d[field]).filter(Boolean))].sort();
    },
    /** Count by category */
    countBy(field, val) {
        return window.ARMORY_DATA.filter(d => d[field] === val).length;
    },
};